language: generic
services:
  - docker

before_install:
    - docker build -t client -f client/Dockerfile.dev client/

cache: npm

before_script: cd client

script:
  - docker run -e CI=true client npm run test

after_success:
  - docker build -t client ./client
  - docker build -t server ./server
  - docker build -t nginx ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push client
  - docker push server
  - docker push nginx

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'Movies'
  env: 'Movies-env'
  bucket: 'elasticbeanstalk-us-east-2-954313048802'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  
