language: generic
services:
  - docker

before_install:
    - docker build -t client -f client/Dockerfile client/

cache: npm

before_script: cd client

script:
  - docker run -e CI=true client npm run test
