version: '3'
services:
  nginx:
    restart: always
    build: nginx/
    ports:
      - '3030:80'
    depends_on:
      - api
      - client
  api:
    build: server/
    ports:
      - '8080:8080'
  client:
    stdin_open: true
    tty: true        
    build: client/
    ports:
        - '3000:80'
    depends_on:
      - api

