version: '3'
services:
  nginx:
    restart: always
    build: nginx/
    ports:
      - '8080:80'
    depends_on:
      - api
      - client
  api:
    build: server/
    ports:
      - '5000:8080'
    volumes:
      - /app/node_modules
      - ./server:/app/server
  client:
    stdin_open: true
    tty: true        
    build: 
      context: client/
      dockerfile: Dockerfile.dev
    ports:
        - '4000:80'
    volumes:
      - /app/node_modules
      - ./client:/app/client
    depends_on:
      - api

